### ISSUE TITLE
Incomplete name?

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-nist#2]
Our data provides only “Nimeroff” as surname:

https://github.com/relaton/relaton-data-nist/blob/main/data/NBS_IR_74-603.yaml#L36

However, DOI lookup provides `family: "Nimeroff", given: "I"`.

Possibly, “I” is an initial that we have unintentionally dropped?

**Comment by ronaldtse** [comment]
The source:

```xml
               <contributors>
                  <person_name sequence="first" contributor_role="author">
                     <given_name>I</given_name>
                     <surname>Nimeroff</surname>
                  </person_name>
               </contributors>
```

Then this is a bug with relaton-nist. @andrew2net can you help check?

**Comment by ronaldtse** [comment]
Filed here: https://github.com/relaton/relaton-nist/issues/65

**Comment by andrew2net** [comment]
fixed
