### ISSUE TITLE
Seemingly bad punctuation in title

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-nist#3]
Case: https://github.com/ietf-ribose/relaton-data-nist/blob/main/data/NBS_SP_260-62.yaml#L5

```yaml
  content: Standard Reference Materials :SRM 768 /
```

**Comment by ronaldtse** [comment]
The data is faithful to the authoritative source. This is an issue with the authoritative source.
https://pages.nist.gov/NIST-Tech-Pubs/SP260.html
<img width="436" alt="Screenshot 2022-01-24 at 12 01 41 AM" src="https://user-images.githubusercontent.com/11865/150687114-89896f15-09ab-409d-a23f-602912f5ca43.png">

https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nbsspecialpublication260-62.pdf
<img width="801" alt="Screenshot 2022-01-24 at 12 02 38 AM" src="https://user-images.githubusercontent.com/11865/150687138-14d04577-0e6d-4cfb-8773-e26fc151111f.png">

Will file this at Relaton and NIST.

**Comment by ronaldtse** [comment]
Posted to:
* https://github.com/relaton/relaton-nist/issues/67
* https://github.com/usnistgov/NIST-Tech-Pubs/issues/10

**Comment by ronaldtse** [comment]
Closing this since there's nothing further to do here (the outstanding tickets will be addressed).
