### ISSUE TITLE
Document versions do not relate to each other

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-nist#5]
Items returned by this search are versions of the same document: https://dev.bibxml.org/search/?query=NIST+CSWP+02042022&allow_format_fallback=True&bypass_cache=True

However, they do not have any relations or shared series (the only shared series is “NIST” as a whole). This means if a visitor somehow lands on https://dev.bibxml.org/get-one/by-docid/?docid=NIST+CSWP+02042022-2&doctype=NIST, they can’t be informed that a newer version exists.

This is reminiscent of https://github.com/ietf-ribose/relaton-data-ids/issues/6, apparently it doesn’t only happen with I-Ds.

I imagine we should use one or more of similar solutions:

- Specify superseded/supersedes relations between such documents
- Specify an additional “series” attribute shared across these documents
  - Optionally, generate an unversioned bibitem for each of such series

**Comment by ronaldtse** [comment]
This is not true. NIST CSWPs are independently published documents and occasionally they are updates, but there is no way for us to know if that is the case because the dates DO NOT indicate any sequence. The date is ONLY use to distinguish if more than one document is published on the same day -- most if not all of the time, these documents have no relationship to each other.

**Comment by ronaldtse** [comment]
There are in fact series of documents in NIST and also editions and revisions of NIST Tech Pubs. However, they do not use a simplistic model as Internet-Drafts. 

You can see the NIST PubID project to understand the complexity of this dataset -- it is not even dealt with by the NIST Information Services Office. (Check out the Metanorma blog article for NIST PubID.)

We cannot handle this within the scope of the BibXML Service project -- the same applies to IEEE, 3GPP.

**Comment by strogonoff** [comment]
Fair enough, they seem to be different.
